name: simply_noted
description: A simple app in which you can create and view a list of text notes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 2.0.13
  timeago: ^3.2.2

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
